yatube/about/urls.py
from django import views
from . import views
from django.urls import path


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path(
        'group/<slug:slug>/',
        views.group_posts,
        name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('create/', views.post_create, name='post_create'),
]

yatube/users/urls.py
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'login/', LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

yatube/about/models.py
# Create your models here.

yatube/core/models.py
# Create your models here.

yatube/posts/models.py
from django.db import models

# Create your models here.
from django.contrib.auth import get_user_model

# Автоматически создаём таблицу для пользователя
User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор поста'
    )
    group = models.ForeignKey(
        'Group',
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='posts',
        verbose_name='Группа, в которой находится пост'
    )

    def __str__(self) -> str:
        return self.text[:15]

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

yatube/posts/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('group', 'text')
        labels = {'text': 'Текст', 'group': 'Группа'}
        help_texts = {
            'text': 'Текст нового поста',
            'group': 'Группа, к которой будет относиться пост',
        }

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/about/views.py
from django.views.generic.base import TemplateView


# Create your views here.
class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Group, User
from .forms import PostForm
from django.contrib.auth.decorators import login_required
from .utils import paginate_page


def is_author(func):
    def check_user(request, *args, **kwargs):
        if Post.author == request.user:
            return func(request, *args, **kwargs)
        return redirect('/auth/login')
    return check_user


def index(request):
    template = 'posts/index.html'
    posts = Post.objects.select_related('group', 'author')
    page_obj = paginate_page(request, posts)
    context: dict = {
        'page_obj': page_obj
    }
    return render(request, template, context)


def group_posts(request, slug):
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.select_related('author', 'group')
    page_obj = paginate_page(request, posts)
    context: dict = {
        'group': group,
        'page_obj': page_obj
    }
    return render(request, template, context)


def profile(request, username):
    template = 'posts/profile.html'
    user = get_object_or_404(User, username=username)
    user_posts = user.posts.select_related('author', 'group')
    page_obj = paginate_page(request, user_posts)
    context: dict = {
        'author': user,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def post_detail(request, post_id):
    template = 'posts/post_detail.html'
    post = get_object_or_404(Post, pk=post_id)
    context: dict = {
        'post': post
    }
    return render(request, template, context)


@login_required
def post_create(request):
    template = 'posts/create_post.html'
    form = PostForm(request.POST or None)
    if form.is_valid():
        new_post = form.save(commit=False)
        new_post.author = request.user
        new_post.save()
        return redirect('posts:profile', request.user)
    return render(request, template, {'form': form})


@login_required
def post_edit(request, post_id):
    template = 'posts/create_post.html'
    is_edit = True
    post = get_object_or_404(Post,
                             pk=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id)
    form = PostForm(request.POST or None, instance=post)
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)
    return render(request, template, context={
        'form': form,
        'post': post,
        'is_edit': is_edit
    })

yatube/users/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/templates/about/author.html
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
<h1>Привет, я автор</h1>
<p>
  Меня зовут Аня.<br> 
  У меня нет кота, но я мечтаю о нём, чтобы он помогал мне кодить.<br>
  <a href=https://github.com/lojiver/> Моя страничка на GitHub. </a>
</p>
{% endblock %} 

yatube/templates/about/tech.html
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% block content %}
{% comment %} Колонки с отступом сверху и снизу {% endcomment %}
<div class="row">
  <h1>Вот что я умею</h1>
  {% comment %}
    Боковой блок со списком технологий 
    Займет всю ширину блока на мобильном
    и 25% при размерах экрана ≥768px
  {% endcomment %}
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Python 3.7
      </li>
      <li class="list-group-item">
        Django 2.2.10
      </li>
    </ul>
  </aside>
  {% comment %}
    Статья  
    Займет всю ширину блока на мобильном
    и 75% при размерах экрана ≥768px
  {% endcomment %}
  <article class="col-12 col-md-9">
    <p></p>
  </article>
</div>
{% endblock %} 

yatube/templates/base.html
<!DOCTYPE html> <!-- Используется html 5 версии -->
{% load static %}
<html lang="ru"> <!-- Язык сайта - русский -->
  <head>    
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href={% static "css/bootstrap.min.css"%}>
    <title> 
    {% block title %} 
    Загадочная страница 
    {% endblock title %} 
    </title>
  </head>
  <body>
    <header>
        {% include 'includes/header.html' %}
    </header>
  <main> 
      
        {% block content %}
        Загадочный контент на странице
        {% endblock content %}
  </main>
    <footer>
        {% include 'includes/footer.html' %}     
    </footer>
  </body>
</html>

yatube/templates/includes/error_control.html
{% if form.errors %}
    {% for field in form %} 
        {% for error in field.errors %}            
            <div class="alert alert-danger">
                {{ error|escape }}
            </div>
        {% endfor %}
    {% endfor %}
{% for error in form.non_field_errors %}
    <div class="alert alert-danger">
        {{ error|escape }}
    </div>
{% endfor %}
{% endif %}       

yatube/templates/includes/footer.html
<div class="border-top text-center py-3">
  <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p> 
  </div>

yatube/templates/includes/header.html
<!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
      <!-- В дальнейшем тут будет создано полноценное меню -->    
      {% load static %}
      
      <header>
        <nav class="navbar navbar-light" style="background-color: lightskyblue">
          <div class="container">
            <a class="navbar-brand" href="{% url 'posts:index' %}">
              <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
              <span style="color:red">Ya</span>tube
            </a>
            {# Добавлено в спринте #}
      
            {% comment %}
            Меню - список пунктов со стандартными классами Bootsrap.
            Класс nav-pills нужен для выделения активных пунктов 
            {% endcomment %}
            {% with request.resolver_match.view_name as view_name %}
            <ul class="nav nav-pills">
              <li class="nav-item"> 
                <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}"
                href="{% url 'about:author' %}">Об авторе</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}"
                 href="{% url 'about:tech' %}">Технологии</a>
              </li>
              {% if user.is_authenticated %}
              <li class="nav-item"> 
                <a class="nav-link {% if view_name  == 'posts:post_create' %}active{% endif %}"
                href="{% url 'posts:post_create' %}">Новая запись</a>
              </li>
              <li class="nav-item"> 
                <a class="nav-link link-light" href="{% url 'password_change' %}">Изменить пароль</a>
              </li>
              <li class="nav-item"> 
                <a class="nav-link link-light" href="{% url 'users:logout' %}">Выйти</a>
              </li>
              <li class="nav-item"> 
                <a class="nav-link {% if view_name  == 'posts:profile' %}active{% endif %}"
                 href="{% url 'posts:profile' user.username %}">
                Пользователь: {{ user.username }} </a>
              </li>
              {% else %}
              <li class="nav-item"> 
                <a class="nav-link link-light {% if view_name  == 'users:login' %}active{% endif %}"
                 href="{% url 'users:login' %}">Войти</a>
              </li>
              <li class="nav-item"> 
                <a class="nav-link link-light {% if view_name  == 'users:signup' %}active{% endif %}"
                 href="{% url 'users:signup' %}">Регистрация</a>
              </li>
              {% endif %}
            </ul>
            {% endwith %}
            {# Конец добавленого в спринте #}
          </div>
        </nav>      
      </header> 

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}
{% if is_edit %}
Редактировать пост
{% else %}
Новый пост
{% endif %}
{% endblock %}
{% block content %}
<div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">       
            {% if is_edit %}
            Редактировать пост
            {% else %}
            Новый пост
            {% endif %}             
          </div>
          <div class="card-body"> 
            {% load user_filters %} {# Загружаем фильтры #}
             {% include 'includes/error_control.html' %} 
            <form method="post" action=
            {% if is_edit %}
            "{% url 'posts:post_edit' post.pk %}"
            {% else %}
            "{% url 'posts:post_create' %}"
            {% endif %}>
              {% csrf_token %}
              {% for field in form %} 
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  {# К полю ввода добавляем атрибут class #}
                  {{ field|addclass:'form-control' }} 
                    {% if field.help_text %}
                      <small 
                         id="{{ field.id_for_label }}-help"
                         class="form-text text-muted"
                      >
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                </div>
              {% endfor %}
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                  Сохранить
                  {% else %}
                  Добавить
                  {% endif %}      
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
  {% block title %} 
    {{ group.title }}
  {% endblock title %}

  {% block content %}
      <!-- класс py-5 создает отступы сверху и снизу блока -->
      <div class="container py-5">
        <h1>{{ group.title }}</h1>
        <p>
          {{ group.description }} 
        </p>
        {% for post in page_obj %}
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>      
        <p>
          {{ post.text }}
        </p>         
      {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}    
        
      {% include 'posts/includes/paginator.html' %}    
  {% endblock content %}

yatube/templates/posts/includes/paginator.html
{% if posts.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if posts.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ posts.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in posts.paginator.page_range %}
        {% if posts.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if posts.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ posts.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ posts.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
Последние обновления на сайте
{% endblock title %}
  {% block content %}
      <!-- класс py-5 создает отступы сверху и снизу блока -->
      <div class="container py-5">     
        <h1>Это главная страница проекта Yatube</h1>
        {% for post in page_obj %}
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y"}}
          </li>
        </ul>
        <p> {{ post.text }} </p>
        
          {% if post.group %}
            <a href="{% url 'posts:group_list' post.group.slug %}"> все записи группы </a>
          {% if not forloop.last %} <hr> {% endif %}
          {% endif %}
        {% endfor %}
        <!-- под последним постом нет линии -->
        {% include 'posts/includes/paginator.html' %}
      </div>
  {% endblock content %}   

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}
    Пост {{ post|truncatechars:30}}
{% endblock title %}
{% block content %} 
     <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y"}} 
            </li>
            {% if not post.group == null %}   
            <li class="list-group-item">
              Группа: {{ post.group.title }} </br>
              <a href="{% url 'posts:group_list' post.group.slug %}">
                все записи группы
              </a>
            </li>
            {% endif %}
            <li class="list-group-item">
              Автор: {{ post.author.get_full_name }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span > {{ post.author.posts.count }} </span>
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author.username %}">
                все посты пользователя
              </a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          <p>
           {{ post.text|linebreaksbr }}
          </p>
        </article>
        {% if user.username == post.author.username %}
        <a href="{% url 'posts:post_edit' post.pk %}">
                Редактировать запись
              </a>
         {% endif %}     
      </div> 
      {% endblock content %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}
    Профайл пользователя {{ author.get_full_name }}
{% endblock title %}
{% block content %} 
    <div class="container py-5">        
        <h1>Все посты пользователя {{ author.username }} </h1>
        <h3>Всего постов: {{ author.posts.count }} </h3>   
        <article>
          <ul>
            <li>
              Автор: {{ author.get_full_name }}
              {% for post in page_obj %}
              <ul>
                <li>
                  Дата публикации: {{ post.pub_date|date:"d E Y" }}
                </li>
              </ul>      
              <p>
                {{ post.text }}
              </p>
            <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a> </br>
                   
            <a href= {% if not post.group.slug == null %}"{% url 'posts:group_list' post.group.slug %}" {% endif %}>все записи группы {{ post.group.title }} </a>        
              
            {% if not forloop.last %}<hr>{% endif %}
            {% endfor %}  </li>
            </ul>
        </article>
          
        
        {% include 'posts/includes/paginator.html' %}
      </div>
      {% endblock content %}
    

yatube/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %} 

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
            <!-- Тест на внимательность. Без переопределения шаблона этого адреса
            не существует. Нужно что-то делать, иначе все упадет -->
            <a href="../password_reset/" class="btn btn-link">
              Забыли пароль?
            </a>
          </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

yatube/templates/users/password_change_done.html
<!DOCTYPE html> 
<html lang="ru"> 
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="../img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="../img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="../img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="../img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="../css/bootstrap.min.css">
    <title>Пароль изменён</title>
  </head>
  <body>	   
    <header>
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="../posts/index.html">
            <img src="../img/logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
            <span style="color:red">Ya</span>tube
          </a>        
        </div>
      </nav> 
    </header>
    <main>
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Пароль изменён
              </div>
              <div class="card-body"> 
                <p>Пароль изменён успешно</p>
              </div> <!-- card body -->
            </div> <!-- card -->
          </div> <!-- col -->
        </div> <!-- row -->
      </div>
    </main>
	  <footer class="border-top text-center py-3">
      <p>© 2021 Copyright <span style="color:red">Ya</span>tube</p>    
    </footer>
  </body>
</html>

yatube/templates/users/password_change_form.html
<!DOCTYPE html> 
<html lang="ru"> 
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="../img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="../img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="../img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="../img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="../css/bootstrap.min.css">
    <title>Изменение пароля</title>
  </head>
  <body>	   
    <header>
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="">
            <img src="../img/logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
            <span style="color:red">Ya</span>tube
          </a>        
        </div>
      </nav> 
    </header>
    <main>
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Изменить пароль
              </div>
              <div class="card-body">
                <form method="post" action="../users/password_change_form.html">
                  <input type="hidden" name="csrfmiddlewaretoken" value="">
                  <div class="form-group row my-3 p-3">
                    <label for="id_old_password">
                      Старый пароль
                      <span class="required text-danger">*</span>
                    </label>    
                    <input type="password" name="old_password" autofocus class="form-control" required id="id_old_password">
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password1">
                      Новый пароль
                      <span class="required text-danger">*</span>
                    </label>    
                    <input type="password" name="new_password1" class="form-control" required id="id_new_password1">
                      <small id="id_new_password1-help" class="form-text text-muted">
                        <ul><li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li><li>Ваш пароль должен содержать как минимум 8 символов.</li><li>Ваш пароль не может быть одним из широко распространённых паролей.</li><li>Ваш пароль не может состоять только из цифр.</li></ul>
                      </small>
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password2">
                      Подтверждение нового пароля
                      <span class="required text-danger">*</span>
                    </label>    
                    <input type="password" name="new_password2" class="form-control" required id="id_new_password2">
                  </div>
                  <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                      Изменить пароль
                    </button>
                  </div>
                </form>
              </div> <!-- card body -->
            </div> <!-- card -->
          </div> <!-- col -->
        </div> <!-- row -->
      </div>
    </main>
	  <footer class="border-top text-center py-3">
      <p>© 2021 Copyright <span style="color:red">Ya</span>tube</p>    
    </footer>
  </body>
</html>

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
          <div class="card-body">
          {% load user_filters %} {# Загружаем фильтры #}
              {% if form.errors %}
                  {% for field in form %} 
                    {% for error in field.errors %}            
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}

              <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}

              {# Выводим поля в цикле, по отдельности #}
              {% for field in form %} 
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  {# К полю ввода добавляем атрибут class #}
                  {{ field|addclass:'form-control' }} 
                    {% if field.help_text %}
                      <small 
                         id="{{ field.id_for_label }}-help"
                         class="form-text text-muted"
                      >
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}